name: Linux
on:
  release:
    types: [ published ]
  push:
    paths-ignore:
      - '.github/workflows/macos.yml'
      - '.github/workflows/windows.yml'

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: verify format
        run: make clang-format-check
  test:
    needs: lint
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        build-type:
          - Debug
          - Release
        compiler:
          - cpp: g++-12
            c: gcc-12
            gcovExecutable: gcov-12

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Configure CMake
        run: >
          cmake -S . -B ./build
          -DCMAKE_BUILD_TYPE:STRING=${{matrix.build-type}}
          -DSIMPLE_CPP_JWT_WARNINGS_AS_ERRORS:BOOL=ON
          -DOPT_ENABLE_COVERAGE:BOOL=${{ matrix.build-type == 'Debug' }}
        env:
          CC: gcc-12
          CXX: g++-12
      - name: Build
        run: cmake --build ./build -- -j 2
      - name: Test
        working-directory: ./build
        run: ctest . --output-on-failure
      - name: coverage
        working-directory: ./build
        if: ${{ matrix.build-type == 'Debug' }}
        run: |
          sudo apt-get install -y gcovr
          gcovr -r ../ -s --gcov-executable ${{ matrix.compiler.gcovExecutable }} -e ../vendor --xml coverage.xml
      - name: coverage-note
        uses: sukolenvo/coverage-notes-action@v0.4.3
        if: ${{ matrix.build-type == 'Debug' }}
        continue-on-error: true
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          cobertura: build/coverage.xml
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.build-type == 'Release' }}
        with:
          files: |
            build/simple-jwt-*